# Application
base.url=https://crm.anhtester.com/admin/authentication

# Browser: chrome | firefox
browser=chrome
headless=false

# Timeouts (seconds)
implicit.wait=10
explicit.wait=15
page.load.timeout=30

# Credentials
test.email=admin@example.com
test.password=123456

#Add New Customer
add.company=CZHYAN
add.phone=8938483567
add.groupSearch=MCH
add.address=TT
add.city=YCH

#Modify Customer
modify.customerSearch=CZHYAN
modify.address=CBD

#Delete Customer
delete.customerSearch=CZHYAN

#Add New Project
add.projectName=QYY
add.startDate=01-09-2026
add.deadline=30-08-2026

#Delete Project
delete.projectSearch=QYY

# Screenshots
screenshot.directory=screenshots
